### ISSUE TITLE
[BUG] Error when try convert & load schematic

### ISSUE THREAD

**Issue by KorewaLidesu** [Enginecrafter77/imhotepmc#1]
Version: 0.9.1
Schematic import from: Litematica 1.20.1

Snip: https://gist.github.com/KorewaLidesu/d88eccad2049604b2ccf0bee0b2c95bc

Logs:
- `latest.log` : https://mclo.gs/F1euX7w
- `debug.log`: https://mclo.gs/wdiDm1E

Schematic:
[Schale.zip](https://github.com/Enginecrafter77/imhotepmc/files/14553715/Schale.zip)

**Comment by Enginecrafter77** [comment]
Hey! Thanks for submitting the issue.

The error was caused by some missing block properties. I have tried to address it in the commit above (well I will probably have to update my translation tables for that but that will take some time, you can imagine editing 6k+ lines of translation rules is not an easy feat).

Try this build: [ImhotepMC-0.9.2-8.zip](https://www.dropbox.com/scl/fi/0ohpxna8kxue8i0mnz7cv/ImhotepMC-0.9.2-8.jar?rlkey=xaa880w56jr6drq480ies3woj&dl=1)

**Comment by KorewaLidesu** [comment]
The provided artifact fixed issue with schematic not loading.
Thank you for fixed the issue.
